### ISSUE TITLE
Cannot place order although before deadline

### ISSUE THREAD

**Issue by kkerk** [open-csa/open-csa-wp#6]
I am about to place an order as admin on 24/11/2015 for a delivery with deadline on 1/12/2015 at 24:00 but I get a pop-up window with the message "<i>You can not add new or upate your order for this delivery, since its order deadline has been reached. For any additional information, please contact either an administrator or the responsible for this delivery.<\i>".

Further info of the Delivery:
Delivery Date: 3/12/2015
Delivery Start Time: 13:00
Delivery End Time: 17:00
User In Charge: admin
New orders can be submitted?: yes

The same happens with a regular user too. But another regular user could place an order?! She was responsible for the one she could submit an order to but that was the case for the admin, just saying.

Can anyone confirm this bug? (I checked my diffs and there are no changes from my side that could explain it)

**Comment by ekosmas** [comment]
Kosta, I could not reproduce the scenario you describe. I was able to submit an order from administrator, responsible, and simple user for a delivery with the exact details you mention.

**Comment by kkerk** [comment]
I fixed it. There were two problems.
1. My admin was not an administrator(?!)
2. In open-csa-wp-deliveries.php in open_csa_wp_is_deadline_reached(...)  the check was `strtotime($current_time)<strtotime($current_time)`
