### ISSUE TITLE
User order list problem(at least for admin)

### ISSUE THREAD

**Issue by kkerk** [open-csa/open-csa-wp#7]
[See image, I hope you can see it] There is one order in the database, but something goes wrong. I checked my diffs and there is no change that could make this all my fault. Nevertheless, if you could confirm it, that would be great. 

![screenshot from 2015-11-26 23 24 57](https://cloud.githubusercontent.com/assets/7210594/11430891/2601144e-9496-11e5-92f3-b433405cdf70.png)

**Comment by ekosmas** [comment]
Kostas, some lines before line 705 in (your copy of) open-csa-wp-orders.php, _(..) function is used, instead of __(...). I fixed it.

**Comment by kkerk** [comment]
So it was so simple after all! Thx Lefteris for the fix! Sorry for not
sending you the file yesterday but I just passed from the house, I should
have told you that I couldn't send it.
